### ISSUE TITLE
✨Spring security + JWT 인증을 통한 유저의 역할 및 id 획득

### ISSUE THREAD

**Issue by mobzzzzz** [coupong-wowdeal/coupong-wowdeal#6]
# 기능 설명
JWTProvier를 만들고 CustomAuthenticationFilter를 만들어서 Filter chain에 걸어가지고 기본적인 인증을 진행 후 User의 Id와 Role 에 대한 체크를 쉽게 할 수 있게 작성합니다.

# To-do
- [x] jjwt 의존성 추가
- [x] JwtPlugin 추가
- [x] CustomAuthenticationFilter를 만들어서 Filter chain에 등록 후 Swagger 예외처리
- [x] Access token 기본 로직 취득 가능한 만큼 User 로직 작성
- [x] Swagger 및 H2-Console 사용에 문제 없게 설정

# ETC
